export enum ErrorCodes {
    SLOT_ALREADY_BOOKED = 'SLOT_ALREADY_BOOKED',
    PAST_DATE = 'PAST_DATE',
    PAST_TIME = 'PAST_TIME',
    INVALID_DATE = 'INVALID_DATE',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
}